### ISSUE TITLE
increase code readability with line breaks

### ISSUE THREAD

**Issue by sen1** [jcbritton/intro-data-capstone-biodiversity#1]
https://github.com/jcbritton/intro-data-capstone-biodiversity/blob/233f3a5d2d493561288f6307189b51af27b4849f/Britton%20-%20Python%20Biodiversity%20Project/Britton_Codeacademy_Capstone.py#L129

I would add few line breaks to increase code readability. Code styling is not something we followed closely in this course. However, it is very important. 
```
protection_counts = species.groupby('conservation_status')\
    .scientific_name.nunique().reset_index()\
    .sort_values(by='scientific_name')
```

Read the PEP8 guide for maximum length of a code length:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by jcbritton** [comment]
Thank you.
