### ISSUE TITLE
Use ax.set_title

### ISSUE THREAD

**Issue by sen1** [jcbritton/intro-data-capstone-biodiversity#2]
https://github.com/jcbritton/intro-data-capstone-biodiversity/blob/233f3a5d2d493561288f6307189b51af27b4849f/Britton%20-%20Python%20Biodiversity%20Project/Britton_Codeacademy_Capstone.py#L150-L153

A minor point here. `ax.set_title` sets the title for one subplot while `plt.title` for the whole figure. Since you only have one plot in this figure, it does not really matter which one you use. However, I would use `ax` object if it's available and to be consistent with lines above. I would use `ax.set_ylabel` and `ax.set_title` for the bottom two lines.

**Comment by jcbritton** [comment]
Thank you.
