### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by sen1** [jcbritton/intro-data-capstone-biodiversity#3]
https://github.com/jcbritton/intro-data-capstone-biodiversity/blob/233f3a5d2d493561288f6307189b51af27b4849f/Britton%20-%20Python%20Biodiversity%20Project/Britton_Codeacademy_Capstone.py#L269

Since we only cared about the pvalue here. The other variables are not used. To be little more efficient, you can replace them `_`.
```
 _, p, _, _ = chi2_contingency(contingency) 
```

`_` is a special character in python. Read more here:
https://hackernoon.com/understanding-the-underscore-of-python-309d1a029edc

**Comment by jcbritton** [comment]
Did not know that. Thank you.
