### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [jcbritton/intro-data-capstone-biodiversity#4]
Great work! I probably won’t have much to say here because you pretty much nailed it all the way through.

Your Python work was excellent and very readable. There are a couple points where your code could be accomplished a bit more efficiently, but everything worked the way it was supposed to.

Presentation: I think your graphs look excellent. Graphs do not really belong at the appendix slides. Embed those plots in slides where you are describing the data. The title should be `Statistical significance calculations` rather than `significant calculation`.

Your conclusions/recommendations are interesting. Hope you get to play more with this data or another!

Excellent work overall.

**Comment by jcbritton** [comment]
Thank you.
